### ISSUE TITLE
Pick a license, add license stuff and reuse linter

### ISSUE THREAD

**Issue by avnik** [mlabs-haskell/cardano.nix#10]
Before opening, project need a license

**Comment by aciceri** [comment]
I believe MIT should be fine.

**Comment by avnik** [comment]
we agreed about "Apache-2.0", I add license stuff as well as license linter to "flake check" sequence

**Comment by aciceri** [comment]
Yeah feel free to add the license. I'm not sure to understand what you mean by license linter instead.
In [mlabs-haskell/spo-anywhere](https://github.com/mlabs-haskell/spo-anywhere/blob/master/LICENSE) I simply added [this file](https://github.com/mlabs-haskell/spo-anywhere/blob/master/LICENSE). If it could be done better in your opinion then please fix it also there.

**Comment by avnik** [comment]
Closed by #15
