### ISSUE TITLE
Show internal options in automatically generated docs

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/cardano.nix#13]
Not sure if we really want to show internal options.

Relevant links:
- https://github.com/NixOS/nixpkgs/tree/nixos-unstable/pkgs/tools/nix/nixos-render-docs
- https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/make-options-doc/default.nix

**Comment by avnik** [comment]
Optional filtering is nearly impossible to implement, without patching nixpkgs. Is hardcoded in https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/make-options-doc/default.nix
