### ISSUE TITLE
Are `statix`, `deadnix` and `prettier` really working?

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/cardano.nix#23]
Or I always write perfect code (🤔) or they are useless because they don't catch interesting cases or something is misconfigured.

**Comment by zmrocze** [comment]
Does it integrate with pre-commit checks? Would be cool if formatter run on pre-commit (got used to that suprisingly quickly).

**Comment by brainrake** [comment]
- treefmt is configured to run it
- it runs on pre-commit
- it actually changes the file  but then fails. i don't like it. it should not change the files when checking correctness in pre-commit hook, only on `nix fmt`
