### ISSUE TITLE
NixOS module for `cardano-node`

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/cardano.nix#27]
We should re-use the [upstream NixOS module](https://github.com/IntersectMBO/cardano-node/blob/master/nix/nixos/cardano-node-service.nix) as much as possible.

The convenient "extension" that allows to set values of a configuration file as NixOS options I was talking about is called [freeform modules](https://nixos.org/manual/nixos/stable/#sec-freeform-modules) and it seems that the upstream module already partially implements something similar through [extraNodeConfig](https://github.com/IntersectMBO/cardano-node/blob/a9a61d7b8a5ab0e70f729b4ac44f8a9b1d08f6f4/nix/nixos/cardano-node-service.nix#L579).

Remember to check if the docs are generated accordingly.

This issue's scope is just to make the module work using values from the `globals` module (and possibly adding new options in that module if needed).

Feel free to split this issue into sub issues, in case please link them here as a to do list.

**Comment by brainrake** [comment]
fixed in #45
