### ISSUE TITLE
NixOS test for `cardano-node`

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/cardano.nix#29]
Probably this has to be done together with #27, or at least whoever works on #27 wants to implement a minimal test to check that the module he's hacking on really works as expected.

Take a look at what is done upstream, perhaps they already implemented NixOS modules.

The optimal solution would be starting a local network, which could be useful also for `SPO-anywhere`.

It would nice also writing an Hercules CI effect that run an overriden NixOS test derivation allowing the QEMU to access the internet (I believe that by default the VM uses a custom network, it's not online **only** because it's sandboxed).
Feel free to experiment this.

Also if you need you can split this issue into sub issues, in case please link them here as a to do list.

**Comment by brainrake** [comment]
fixed in #45
