### ISSUE TITLE
`run-vm-test -l` shows also impure tests

### ISSUE THREAD

**Issue by aciceri** [mlabs-haskell/cardano.nix#63]
See [here](https://github.com/mlabs-haskell/cardano.nix/blob/06123972663947e360b23e67e64875d93bad181d/checks/run-vm-test.nix#L38).

**Comment by brainrake** [comment]
I think it should show and run impure tests. But can it run them?

**Comment by aciceri** [comment]
I think I wanted to write "should show also impure tests"

But I believe this is fixed and can be closed now.
```
$ run-vm-test --list
  list of available tests:

    - blockfrost
    - cardano-cli
    - cardano-node
    - ctl-8
    - db-sync
    - http
    - kupo
    - ogmios
    - oura
```

This includes impure tests (all the tests are impure?) and can run them (just tested).
