### ISSUE TITLE
Oura

### ISSUE THREAD

**Issue by nrutledge** [mlabs-haskell/cardano.nix#84]
We have chosen Oura as one of the services for milestone 4. Below is a breakdown of the outputs and acceptance criteria from https://milestones.projectcatalyst.io/projects/1000126/milestones/4 

Outputs:
- [ ] The needed NixOS module(s), optionally importing it(them) and/or wrapping it(them) in a more homogenous interface
- [ ] The needed NixOS tests (executed on the CI)
- [ ] The automatically generated documentation on the website
- [ ] Optionally, we will condense services into large modules, “super-modules” as referred to in the original IdeaScale proposal, providing an easy and opinionated way of starting these sets of services

Acceptance Criteria:
- [ ] The intended services have been successfully wrapped or otherwise processed as outlined above.
- [ ] Tests run successfully on the processed services.
- [ ] Documentation is updated, readable, and reflects the processed services.

**Comment by aciceri** [comment]
[Here](https://github.com/mlabs-haskell/equine-devops/blob/master/modules/oura/default.nix) a starting point.

**Comment by nrutledge** [comment]
Closed by #92
